/********************************************************************
 *   This C program was generated by spl2c, the Shakespeare to C    *
 *          converter by Jon Åslund and Karl Hasselström.           *
 ********************************************************************/

/* libspl definitions and function prototypes */
#include <spl.h>

int main(void)
{
  /******************************************************************
   * A TALE OF TWO CITES ( SIC )                                    *
   ******************************************************************/
  
  CHARACTER *julius_caesar;               /* the first citizen of the Roman Republic */
  CHARACTER *brutus;                      /* a traitor - - member of the Fifth Column */
  CHARACTER *cicero;                      /* the greatest Roman orator */
  CHARACTER *cleopatra;                   /* a proud queen , whom the Romans want to make one of their own */
  CHARACTER *romeo;                       /* a man who ' s sometimes there */
  CHARACTER *juliet;                      /* a maiden who can follow Romeo or stand on her own */
  
  int comp1, comp2;
  
  global_initialize();
  
  julius_caesar = initialize_character("Julius Caesar");
  brutus = initialize_character("Brutus");
  cicero = initialize_character("Cicero");
  cleopatra = initialize_character("Cleopatra");
  romeo = initialize_character("Romeo");
  juliet = initialize_character("Juliet");
  
  act_i:                                  /* Imperium Romanum */
  
  act_i_scene_i:                          /* Cleopatra puts men in their place */
  
  enter_scene(16, cleopatra);
  enter_scene(16, julius_caesar);
  
  activate_character(22, julius_caesar);
  assign(19, second_person, int_add(19, 2*2*2*2*2*1, 2*2*2*1));
  char_output(20, second_person);
  char_input(20, second_person);
  char_input(20, second_person);
  char_input(20, second_person);
  char_input(20, second_person);
  
  activate_character(26, cleopatra);
  assign(24, second_person, int_add(23, 2*2*2*1, int_add(23, 1, 2*2*2*2*2*2*1)));
  
  exit_scene(26, julius_caesar);
  
  enter_scene(27, brutus);
  
  activate_character(34, cleopatra);
  assign(30, second_person, int_sub(30, 2*1, (-1)));
  assign(31, second_person, int_sub(31, value_of(31, second_person), 2*2*2*2*1));
  assign(32, second_person, int_sub(32, julius_caesar->value, value_of(32, second_person)));
  
  exit_scene(34, brutus);
  
  enter_scene(35, cicero);
  
  activate_character(41, cleopatra);
  assign(38, second_person, int_sub(38, brutus->value, 2*(-1)));
  
  act_i_scene_ii:                         /* How do you solve a problem like Cleopatra */
  
  exit_scene_all(43);
  
  enter_scene(44, cleopatra);
  enter_scene(44, julius_caesar);
  
  activate_character(49, julius_caesar);
  int_input(47, second_person);
  
  exit_scene(49, cleopatra);
  
  enter_scene(50, brutus);
  
  activate_character(55, julius_caesar);
  comp1 = cleopatra->value;
  comp2 = 2*2*2*1;
  truth_flag = (comp1 > comp2);
  
  activate_character(58, brutus);
  if (truth_flag) {
    goto act_i_scene_iv;
  }
  comp1 = cleopatra->value;
  comp2 = 2*2*1;
  truth_flag = !(comp1 < comp2);
  
  activate_character(61, julius_caesar);
  if (truth_flag) {
    goto act_i_scene_iii;
  }
  
  activate_character(64, brutus);
  char_output(62, second_person);
  
  activate_character(67, julius_caesar);
  comp1 = cleopatra->value;
  comp2 = 1;
  truth_flag = (comp1 > comp2);
  
  activate_character(70, brutus);
  if (truth_flag) {
    char_output(68, second_person);
  }
  
  activate_character(73, julius_caesar);
  comp1 = cleopatra->value;
  comp2 = 2*1;
  truth_flag = (comp1 > comp2);
  
  activate_character(76, brutus);
  if (truth_flag) {
    char_output(74, second_person);
  }
  
  activate_character(80, julius_caesar);
  goto act_i_scene_v;
  
  act_i_scene_iii:                        /* Brutus and his friends */
  
  activate_character(84, julius_caesar);
  comp1 = cleopatra->value;
  comp2 = 2*2*1;
  truth_flag = (comp1 == comp2);
  
  activate_character(87, brutus);
  if (truth_flag) {
    char_output(85, second_person);
  }
  
  activate_character(90, julius_caesar);
  char_output(88, second_person);
  
  activate_character(93, julius_caesar);
  comp1 = cleopatra->value;
  comp2 = int_add(91, 2*2*1, 1);
  truth_flag = (comp1 > comp2);
  
  activate_character(96, brutus);
  if (truth_flag) {
    char_output(94, second_person);
  }
  
  activate_character(99, julius_caesar);
  comp1 = cleopatra->value;
  comp2 = int_add(97, 2*2*1, 2*1);
  truth_flag = (comp1 > comp2);
  
  activate_character(102, brutus);
  if (truth_flag) {
    char_output(100, second_person);
  }
  
  activate_character(105, julius_caesar);
  comp1 = cleopatra->value;
  comp2 = 2*2*2*1;
  truth_flag = (comp1 == comp2);
  
  activate_character(108, brutus);
  if (truth_flag) {
    char_output(106, second_person);
  }
  
  activate_character(112, julius_caesar);
  goto act_i_scene_v;
  
  act_i_scene_iv:                         /* Cicero is asked to speak */
  
  exit_scene(113, brutus);
  
  enter_scene(114, cicero);
  
  activate_character(119, julius_caesar);
  comp1 = cleopatra->value;
  comp2 = int_add(117, 2*2*2*1, 1);
  truth_flag = (comp1 == comp2);
  
  activate_character(122, cicero);
  if (truth_flag) {
    char_output(120, second_person);
  }
  
  activate_character(126, julius_caesar);
  char_output(123, second_person);
  
  act_i_scene_v:                          /* A period piece - - Cleopatra ' s reprisal */
  
  exit_scene_all(127);
  
  enter_scene(128, cleopatra);
  enter_scene(128, julius_caesar);
  
  activate_character(136, julius_caesar);
  assign(132, second_person, int_add(131, 2*2*2*2*2*1, 2*2*2*2*1));
  assign(133, second_person, int_sub(133, value_of(133, second_person), 2*1));
  char_output(133, second_person);
  char_input(134, second_person);
  char_input(134, second_person);
  char_input(134, second_person);
  char_input(134, second_person);
  char_input(134, second_person);
  char_input(134, second_person);
  
  activate_character(139, cleopatra);
  comp1 = value_of(137, second_person);
  comp2 = int_add(137, 2*2*2*2*2*2*1, 2*2*2*2*2*1);
  truth_flag = (comp1 > comp2);
  
  activate_character(142, julius_caesar);
  if (truth_flag) {
    goto act_ii;
  }
  char_input(140, second_person);
  char_input(140, second_person);
  
  activate_character(145, cleopatra);
  assign(143, second_person, int_sub(143, value_of(143, second_person), 2*2*2*2*2*(-1)));
  
  exit_scene(145, julius_caesar);
  
  enter_scene(146, brutus);
  
  activate_character(151, cleopatra);
  assign(149, second_person, int_sub(149, value_of(149, second_person), 2*2*2*2*2*(-1)));
  
  exit_scene(151, brutus);
  
  enter_scene(152, cicero);
  
  activate_character(159, cleopatra);
  assign(155, second_person, int_sub(155, brutus->value, 2*(-1)));
  goto act_i_scene_ii;
  
  act_ii:                                 /* Lovers ' arithmetick */
  
  act_ii_scene_i:                         /* Our lovers discuss what they have in common */
  
  exit_scene_all(163);
  
  enter_scene(164, romeo);
  enter_scene(164, juliet);
  
  activate_character(169, romeo);
  assign(167, second_person, (-1));
  int_input(167, second_person);
  
  activate_character(172, juliet);
  comp1 = value_of(170, first_person);
  comp2 = 0;
  truth_flag = (comp1 > comp2);
  if (truth_flag) {
    goto act_ii_scene_iii;
  }
  
  activate_character(175, romeo);
  char_input(173, second_person);
  char_input(173, second_person);
  
  activate_character(178, juliet);
  int_input(176, second_person);
  int_output(176, second_person);
  
  activate_character(187, romeo);
  assign(180, second_person, int_mul(179, int_sub(179, 2*2*2*2*1, 1), int_add(180, 2*1, 1)));
  char_output(180, second_person);
  char_input(180, second_person);
  int_input(181, second_person);
  comp1 = int_div(181, value_of(181, second_person), int_add(181, int_add(181, 2*2*2*2*2*2*1, 2*2*2*2*2*1), 2*2*1));
  comp2 = int_div(183, value_of(184, first_person), int_add(184, int_add(184, 2*2*2*2*2*2*1, 2*2*2*2*2*1), 2*2*1));
  truth_flag = (comp1 == comp2);
  
  activate_character(190, juliet);
  if (!truth_flag) {
    goto act_ii_scene_ii;
  }
  
  activate_character(195, romeo);
  assign(193, second_person, int_mod(191, value_of(191, second_person), int_add(191, int_add(191, 2*2*2*2*2*2*1, 2*2*2*2*2*1), 2*2*1)));
  
  activate_character(201, juliet);
  assign(198, second_person, int_mod(196, value_of(196, second_person), int_add(196, int_add(196, 2*2*2*2*2*2*1, 2*2*2*2*2*1), 2*2*1)));
  
  act_ii_scene_ii:                        /* Tense times */
  
  activate_character(207, juliet);
  comp1 = int_div(203, value_of(203, second_person), int_add(203, 2*2*2*1, 2*1));
  comp2 = int_div(204, value_of(204, first_person), int_add(204, 2*2*2*1, 2*1));
  truth_flag = (comp1 == comp2);
  
  activate_character(212, romeo);
  if (truth_flag) {
    assign(209, second_person, int_mod(208, value_of(209, second_person), int_add(209, 2*2*2*1, 2*1)));
  }
  
  act_ii_scene_iii:                       /* Parting is such sweet sorrow */
  
  activate_character(216, romeo);
  int_output(214, second_person);
  assign(215, second_person, int_add(214, 2*2*2*2*2*1, int_add(214, 2*2*2*1, 1)));
  char_output(215, second_person);
  
  return 0;
}
